Add sanity checks to get_password_from_credhub
[#172482424](https://www.pivotaltracker.com/story/show/172482424)

Co-authored-by: Andrew Wittrock <awittrock@pivotal.io>

diff --git a/shared-functions b/shared-functions
--- a/shared-functions
+++ b/shared-functions
@@ -326,6 +326,19 @@ write_gcp_service_account_key() {
 get_password_from_credhub() {
   set +x
   local bosh_manifest_password_variable_name=$1
+
+  local credential_path=$(credhub find -j -n ${bosh_manifest_password_variable_name} | jq -r .credentials[].name )
+  local credential_paths_len=$(echo ${credential_path} | tr ' ' '\n' | wc -l)
+
+  if [ "${credential_paths_len}" -gt 1 ]; then
+    echo "ambiguous ${bosh_manifest_password_variable_name} variable name; expected one got ${credential_paths_len}" >&2
+    echo "${credential_path}" | tr ' ' '\n' >&2
+    return
+  elif [ "${credential_paths_len}" -eq 0 ]; then
+    echo "${bosh_manifest_password_variable_name} variable not found" >&2
+    return
+  fi
+
   echo $(credhub find -j -n ${bosh_manifest_password_variable_name} | jq -r .credentials[].name | xargs credhub get -j -n | jq -r .value)
   set -x
 }
